name: Dev Deployment
# This workflow is triggered on pushes to the development branch
# It builds the project and deploys it to the FTP server

on:
  push:
    branches:
     - development

jobs:
  build:
    name: Build & Deploy IMBIT-PIXELS Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build website
        run: npm run build

      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}