export const dialogueData = {
    ksb001: {
      title: 'IMBIT Studium',
      text: 'Im IMBIT-Studium kombinierst du internationale BWL mit IT – und das alles auf Englisch an der DHBW Mannheim!',
      answers: [],
    },
    ksb002: {
      title: 'KSB Info',
      text: 'Wusstest du, dass KSB schon seit 1871 existiert? Heute ist das Unternehmen weltweit aktiv in über 150 Ländern!',
      answers: [],
    },
    ksb003: {
      title: 'Duales Studium',
      text: 'Ein duales Studium bei KSB bedeutet: Du studierst an der DHBW und arbeitest im Unternehmen – perfekte Kombination aus Theorie und Praxis!',
      answers: [],
    },
    ksb004: {
      title: 'Duales Studium',
      text: 'Ein duales Studium bei KSB bedeutet: Du studierst an der DHBW und arbeitest im Unternehmen – perfekte Kombination aus Theorie und Praxis!',
      answers: [],
    },
    ksb005: {
      title: 'IMBIT Studium',
      text: 'Im IMBIT-Studium kombinierst du internationale BWL mit IT – und das alles auf Englisch an der DHBW Mannheim!',
      answers: [],
    },
    ksb006: {
      title: 'Ausbildung bei KSB',
      text: 'KSB bildet in vielen technischen und kaufmännischen Berufen aus – darunter Mechatroniker, Industriekaufleute und Gießereimechaniker.',
      answers: [],
    },
    ksb007: {
      title: 'Quiz zu KSB',
      text: 'Wie viele Mitarbeitende arbeiten weltweit bei KSB?',
      answers: ['Etwa 5.000', 'Etwa 10.000', 'Etwa 16.000'],
      correctAnswer: 3,
      correctText: 'Richtig! KSB beschäftigt rund 16.000 Menschen weltweit.',
      wrongText: 'Nicht ganz – die richtige Zahl ist rund 16.000!',
    },
    ksb008: {
      title: 'Quiz zu KSB',
      text: 'Wie viele Mitarbeitende arbeiten weltweit bei KSB?',
      answers: ['Etwa 5.000', 'Etwa 10.000', 'Etwa 16.000'],
      correctAnswer: 3,
      correctText: 'Richtig! KSB beschäftigt rund 16.000 Menschen weltweit.',
      wrongText: 'Nicht ganz – die richtige Zahl ist rund 16.000!',
    },
    ksb009: {
      title: 'Quiz zur Ausbildung',
      text: 'Wie lange dauert eine typische Ausbildung bei KSB?',
      answers: ['2 Jahre', '3 Jahre', '4 Jahre'],
      correctAnswer: 2,
      correctText: 'Genau! Die meisten Ausbildungen dauern 3 Jahre.',
      wrongText: 'Leider falsch – meistens dauert eine Ausbildung 3 Jahre.',
    },
    ksb010: {
      title: 'Ausbildung bei KSB',
      text: 'KSB bildet in vielen technischen und kaufmännischen Berufen aus – darunter Mechatroniker, Industriekaufleute und Gießereimechaniker.',
      answers: [],
    },
    ksb011: {
      title: 'Quiz zu KSB',
      text: 'Wie viele Mitarbeitende arbeiten weltweit bei KSB?',
      answers: ['Etwa 5.000', 'Etwa 10.000', 'Etwa 16.000'],
      correctAnswer: 3,
      correctText: 'Richtig! KSB beschäftigt rund 16.000 Menschen weltweit.',
      wrongText: 'Nicht ganz – die richtige Zahl ist rund 16.000!',
    },
    ksb012: {
      title: 'Quiz zum IMBIT',
      text: 'Was bedeutet IMBIT?',
      answers: ['International Management for Business and IT', 'Industrial Methods for Business in IT', 'Integrated Models for Banking and IT'],
      correctAnswer: 1,
      correctText: 'Richtig! IMBIT steht für International Management for Business and IT.',
      wrongText: 'Leider falsch – es steht für International Management for Business and IT.',
    },
    ksb013: {
      title: 'Quiz zum IMBIT',
      text: 'Was bedeutet IMBIT?',
      answers: ['International Management for Business and IT', 'Industrial Methods for Business in IT', 'Integrated Models for Banking and IT'],
      correctAnswer: 1,
      correctText: 'Richtig! IMBIT steht für International Management for Business and IT.',
      wrongText: 'Leider falsch – es steht für International Management for Business and IT.',
    },
    ksb014: {
      title: 'KSB Info',
      text: 'Wusstest du, dass KSB schon seit 1871 existiert? Heute ist das Unternehmen weltweit aktiv in über 150 Ländern!',
      answers: [],
    },
    ksb015: {
      title: 'Ausbildung bei KSB',
      text: 'KSB bildet in vielen technischen und kaufmännischen Berufen aus – darunter Mechatroniker, Industriekaufleute und Gießereimechaniker.',
      answers: [],
    },
    ksb016: {
      title: 'Duales Studium',
      text: 'Ein duales Studium bei KSB bedeutet: Du studierst an der DHBW und arbeitest im Unternehmen – perfekte Kombination aus Theorie und Praxis!',
      answers: [],
    },
    ksb017: {
      title: 'Quiz zum IMBIT',
      text: 'Was bedeutet IMBIT?',
      answers: ['International Management for Business and IT', 'Industrial Methods for Business in IT', 'Integrated Models for Banking and IT'],
      correctAnswer: 1,
      correctText: 'Richtig! IMBIT steht für International Management for Business and IT.',
      wrongText: 'Leider falsch – es steht für International Management for Business and IT.',
    },
    ksb018: {
      title: 'Quiz zu KSB',
      text: 'Wie viele Mitarbeitende arbeiten weltweit bei KSB?',
      answers: ['Etwa 5.000', 'Etwa 10.000', 'Etwa 16.000'],
      correctAnswer: 3,
      correctText: 'Richtig! KSB beschäftigt rund 16.000 Menschen weltweit.',
      wrongText: 'Nicht ganz – die richtige Zahl ist rund 16.000!',
    },
    ksb019: {
      title: 'IMBIT Studium',
      text: 'Im IMBIT-Studium kombinierst du internationale BWL mit IT – und das alles auf Englisch an der DHBW Mannheim!',
      answers: [],
    },
    ksb020: {
      title: 'Duales Studium',
      text: 'Ein duales Studium bei KSB bedeutet: Du studierst an der DHBW und arbeitest im Unternehmen – perfekte Kombination aus Theorie und Praxis!',
      answers: [],
    },
    ksb021: {
      title: 'KSB Info',
      text: 'Wusstest du, dass KSB schon seit 1871 existiert? Heute ist das Unterksbnehmen weltweit aktiv in über 150 Ländern!',
      answers: [],
    },
    ksb022: {
      title: 'Ausbildung bei KSB',
      text: 'KSB bildet in vielen technischen und kaufmännischen Berufen aus – darunter Mechatroniker, Industriekaufleute und Gießereimechaniker.',
      answers: [],
    },
    ksb023: {
      title: 'Quiz zum IMBIT',
      text: 'Was bedeutet IMBIT?',
      answers: ['International Management for Business and IT', 'Industrial Methods for Business in IT', 'Integrated Models for Banking and IT'],
      correctAnswer: 1,
      correctText: 'Richtig! IMBIT steht für International Management for Business and IT.',
      wrongText: 'Leider falsch – es steht für International Management for Business and IT.',
    },
    ksb024: {
      title: 'KSB Info',
      text: 'Wusstest du, dass KSB schon seit 1871 existiert? Heute ist das Unternehmen weltweit aktiv in über 150 Ländern!',
      answers: [],
    },
    ksb025: {
      title: 'Ausbildung bei KSB',
      text: 'KSB bildet in vielen technischen und kaufmännischen Berufen aus – darunter Mechatroniker, Industriekaufleute und Gießereimechaniker.',
      answers: [],
    },
    ksb026: {
      title: 'Quiz zu KSB',
      text: 'Wie viele Mitarbeitende arbeiten weltweit bei KSB?',
      answers: ['Etwa 5.000', 'Etwa 10.000', 'Etwa 16.000'],
      correctAnswer: 3,
      correctText: 'Richtig! KSB beschäftigt rund 16.000 Menschen weltweit.',
      wrongText: 'Nicht ganz – die richtige Zahl ist rund 16.000!',
    },
  };